version: 0.2

env:
  variables:
    IMAGE_NAME: irfantechno/issc-api

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_NAME:latest .
      - docker push $IMAGE_NAME:latest

post_build:
  commands:
    - echo Deploying to Kubernetes...
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@16.16.218.161 "kubectl create namespace issc --dry-run=client -o yaml | kubectl apply -f - && kubectl apply -f ~/deploy/issc-deploy-dh.yaml && kubectl rollout status deployment/issc-api -n issc --timeout=180s"
